apiVersion: batch/v1
kind: CronJob
metadata:
  name: every-1min-cron
spec:
  schedule: "*/1 * * * *"   # runs every 1 minute
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: busybox
              image: busybox
              command: ["sh", "-c", "echo CronJob executed at $(date)"]
