apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-job
spec:
  parallelism: 3
  completions: 6
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: busybox
          image: busybox
          command: ["sh", "-c", "echo Parallel Job Running; sleep 3"]
