apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-pod
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: test-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: pvc-example   # or pvc-dynamic
